USE BASIC;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL
);
INSERT INTO STUDENT VALUES (1,"RAJ",23);
INSERT INTO STUDENT VALUES (4,"RAJ",10);

SELECT * FROM STUDENT;

CREATE DATABASE IF NOT EXISTS DB1;
DROP DATABASE DB1;
INSERT INTO STUDENT(ID,NAME,AGE) VALUES
(7,"SHAYAM",23),
(8,"RAM",90);
INSERT INTO STUDENT(ID,NAME,AGE) VALUES
(9,"UNOWNN",50);

SELECT NAME ,ID  FROM STUDENT;

CREATE TABLE IF NOT EXISTS STUDENT1 (
    STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    ROLL_NO VARCHAR(20) UNIQUE NOT NULL,
    CLASS VARCHAR(20),
    SECTION VARCHAR(10),
    GENDER VARCHAR(10),
    DATE_OF_BIRTH DATE,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(15),
    ADDRESS TEXT,
    ADMISSION_DATE DATE
);
INSERT INTO STUDENT1
(NAME, ROLL_NO, CLASS, SECTION, GENDER, DATE_OF_BIRTH, EMAIL, PHONE, ADDRESS, ADMISSION_DATE)
VALUES
('AMIT KUMAR', 'RN101', 'BSC', 'A', 'MALE', '2002-01-15', 'AMIT@GMAIL.COM', '9876543201', 'DELHI', '2021-08-01'),
('PRIYA SINGH', 'RN102', 'BCA', 'A', 'FEMALE', '2002-02-20', 'PRIYA@GMAIL.COM', '9876543202', 'NOIDA', '2021-08-01'),
('RAHUL VERMA', 'RN103', 'BSC', 'B', 'MALE', '2002-03-10', 'RAHUL@GMAIL.COM', '9876543203', 'DELHI', '2021-08-01'),
('SNEHA GUPTA', 'RN104', 'MBA', 'B', 'FEMALE', '2001-04-05', 'SNEHA@GMAIL.COM', '9876543204', 'GURGAON', '2021-08-01'),
('ROHIT SHARMA', 'RN105', 'BCA', 'A', 'MALE', '2002-05-18', 'ROHIT@GMAIL.COM', '9876543205', 'FARIDABAD', '2021-08-01'),
('ANJALI MEHTA', 'RN106', 'MSC', 'C', 'FEMALE', '2001-06-25', 'ANJALI@GMAIL.COM', '9876543206', 'DELHI', '2021-08-01'),
('VIKAS YADAV', 'RN107', 'BSC', 'C', 'MALE', '2002-07-30', 'VIKAS@GMAIL.COM', '9876543207', 'MEERUT', '2021-08-01'),
('NEHA PATEL', 'RN108', 'BCA', 'A', 'FEMALE', '2002-08-12', 'NEHA@GMAIL.COM', '9876543208', 'AHMEDABAD', '2021-08-01'),
('SAURABH JAIN', 'RN109', 'MBA', 'B', 'MALE', '2001-09-08', 'SAURABH@GMAIL.COM', '9876543209', 'JAIPUR', '2021-08-01'),
('POOJA MALHOTRA', 'RN110', 'MSC', 'C', 'FEMALE', '2001-10-22', 'POOJA@GMAIL.COM', '9876543210', 'CHANDIGARH', '2021-08-01');

 
 
-- USIING WHERE CLAUSE

SELECT * FROM STUDENT WHERE AGE>=25 && AGE < 90; -- && TWO CONDITION
SELECT * FROM  STUDENT WHERE NAME="RAJ"; 
SELECT * FROM STUDENT WHERE NAME = "RAJ" AND AGE=23 ; -- USING AND OPERATOR
SELECT * FROM STUDENT  WHERE NAME = "SHAYAM" OR AGE= 26; -- OR OPT, ANY ONE TRUE
SELECT * FROM STUDENT WHERE AGE BETWEEN 30 AND 90; -- BETWEEN OPT
SELECT * FROM STUDENT  WHERE ID IN (10); -- MATCH ANY VALUE IN LIST
SELECT * FROM STUDENT WHERE AGE NOT IN (10);
SELECT * FROM STUDENT WHERE NOT AGE='23';


-- LIMIT CLAUSE
SELECT *  FROM STUDENT1 WHERE GENDER= "MALE"
LIMIT 3; -- TOPKI VALUE RETURN KARTE HAI
SELECT NAME , CLASS FROM STUDENT1 WHERE GENDER = "FEMALE"
LIMIT 4;
SELECT *  FROM STUDENT1 WHERE GENDER= "FEMALE"
LIMIT 2;


-- ORDER BY CLAUSE
SELECT * FROM STUDENT1  
ORDER BY ADDRESS;
SELECT * FROM STUDENT1
ORDER BY (SECTION) DESC  -- ORDER SET KARTE HAI ACC OR DEC ORDER ME
LIMIT 5; 

-- AGGREATE FUNCTION
SELECT MAX(EMAIL)FROM STUDENT1;
SELECT MIN(EMAIL)FROM STUDENT1;
SELECT AVG(CLASS)FROM STUDENT1;
SELECT COUNT(ADDRESS)FROM STUDENT1;
SELECT SUM(SECTION)FROM STUDENT1;

SELECT SUM(AGE)FROM STUDENT;


-- GROUP BY CLAUSE
SELECT ID,MAX(AGE) FROM STUDENT
GROUP BY ID
ORDER BY (AGE);

SELECT ADDRESS ,  MIN(NAME) FROM STUDENT1
GROUP BY ADDRESS
ORDER BY ADDRESS ASC
LIMIT 5;

-- HAVING CLAUSE
SELECT ADDRESS ,  MIN(NAME) FROM STUDENT1
GROUP BY ADDRESS  -- APPLIED CONDITION
HAVING AVG(STUDENT_ID) >5;

-- UPDATE
SELECT * FROM STUDENT;
UPDATE STUDENT
SET NAME="RAJU"
WHERE ID=1 AND NAME="RAJ";

-- DELETE
DELETE FROM STUDENT
WHERE NAME = 'RAJ';

 -- ADD CLMN
ALTER TABLE STUDENT
ADD COLUMN GENDER VARCHAR(10);
-- DELETE CLMN  
ALTER TABLE STUDENT
DROP COLUMN GENDER;

ALTER TABLE DATA
RENAME TO STUDENT;


